=== rama-swuni/csf205-2021/week3/sow.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema
        xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.org/sow"
        xmlns:tns="http://www.example.org/sow" elementFormDefault="qualified">
    <complexType name="courseDetailsType">
        <sequence>
            <element name="courseTitle" type="string" maxOccurs="1"
                     minOccurs="1"></element>
            <element name="courseDuration" type="tns:courseDurationType"
                     maxOccurs="1" minOccurs="1"></element>
            <element name="courseInstructor" type="tns:instructorType"
                     maxOccurs="unbounded" minOccurs="1"></element>
            <element name="courseDates" type="tns:courseDateType"
                     maxOccurs="1" minOccurs="1"></element>
        </sequence>
    </complexType>
    <complexType name="courseDurationType">
        <simpleContent>
            <extension base="unsignedByte">
                <attribute name="length" type="string" use="required"></attribute>
            </extension>
        </simpleContent>
    </complexType>
    <complexType name="courseDateType">
        <sequence>
            <element name="startDate" type="string"></element>
            <element name="endDate" type="string"></element>
        </sequence>
    </complexType>
    <complexType name="instructorType">
        <sequence>
            <element name="instructor" type="tns:eachInstructorType" maxOccurs="unbounded" minOccurs="1"></element>
        </sequence>
    </complexType>
    <complexType name="eachInstructorType">
        <simpleContent>
            <extension base="string">
                <attribute name="emailID" type="string" use="required"></attribute>
            </extension>
        </simpleContent>
    </complexType>
    <complexType name="booksRecommendedType">
        <sequence>
            <element name="book" type="tns:booksType" maxOccurs="unbounded" minOccurs="1"></element>
        </sequence>
    </complexType>
    <complexType name="booksType">
        <sequence>
            <element name="title" type="string" />
            <element name="authors">
                <complexType>
                    <sequence>
                        <element maxOccurs="unbounded" name="author"
                                 type="string" />
                    </sequence>
                </complexType>
            </element>
        </sequence>
        <attribute name="isbn10" type="unsignedInt" use="required"></attribute>
    </complexType>
    <complexType name="lectureSyllabusType">
        <sequence>
            <element maxOccurs="unbounded" name="week" minOccurs="1">
                <complexType>
                    <sequence>
                        <element minOccurs="1" maxOccurs="1" name="topics" type="string"/>
                        <element minOccurs="0" maxOccurs="1" name="otherDetails" type="string" />
                        <element minOccurs="0" maxOccurs="1" name="lab" type="string" />
                    </sequence>
                    <attribute name="id" type="int" use="required" />
                    <attribute name="test" type="string" use="optional" />
                    <attribute name="coursework" type="string" use="optional" />
                </complexType>
            </element>
        </sequence>
    </complexType>
    <element name="schemeOfWork" type="tns:sowType"></element>
    <complexType name="sowType">
        <sequence>
            <element name="courseDetails"
                     type="tns:courseDetailsType"></element>
            <element name="booksRecommended"
                     type="tns:booksRecommendedType"></element>
            <element name="lectureSyllabus"
                     type="tns:lectureSyllabusType"></element>
        </sequence>
        <attribute name="courseID" type="string" use="required"></attribute>
    </complexType>
</schema>

=== rama-swuni/csf205-2021/week3/CSF205SoWWithXSDWithNS.xml
<?xml version="1.0" encoding="UTF-8"?>
<sow:schemeOfWork courseID="CSF205"
                  xmlns:sow="http://www.example.org/sow"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://www.example.org/sow sow.xsd ">
    <sow:courseDetails>
        <sow:courseTitle>Data Representation, Markup Languages and Web Services</sow:courseTitle>
        <sow:courseDuration length="months">3</sow:courseDuration>
        <sow:courseInstructor>
            <sow:instructor emailID="r.vaidhiyanathan@swansea.ac.uk">Ramalakshmi Vaidhiyanathan</sow:instructor>
        </sow:courseInstructor>
        <sow:courseDates>
            <sow:startDate>23-Sept-2020</sow:startDate>
            <sow:endDate>16-Dec-2020</sow:endDate>
        </sow:courseDates>
    </sow:courseDetails>
    <sow:booksRecommended>
        <sow:book isbn10="0321269667">
            <sow:title>An Introduction to XML and Web Technologies</sow:title>
            <sow:authors>
                <sow:author>Anders MÃ¸ller</sow:author>
                <sow:author>Michael I. Schwartzbach</sow:author>
            </sow:authors>
        </sow:book>
        <sow:book isbn10="0470114878">
            <sow:title>Beginning XML</sow:title>
            <sow:authors>
                <sow:author>David Hunter</sow:author>
            </sow:authors>
        </sow:book>
    </sow:booksRecommended>
    <sow:lectureSyllabus>
        <sow:week id="1" test="midterm" coursework="1">
            <sow:topics>Introduction to Data Representation,
                Data Presentation, Markup Languages, HTML</sow:topics>
            <sow:lab>HTML</sow:lab>
        </sow:week>
        <sow:week id="2" test="midterm" coursework="1">
            <sow:topics>Presentation and Styling of Data using CSS,
                and Web Accessibility</sow:topics>
            <sow:lab>HTML + CSS</sow:lab>
        </sow:week>
        <sow:week id="3" test="midterm" coursework="1">
            <sow:topics>Introduction to Data Representation using XML,
                XML validation using DTD and Schema</sow:topics>
            <sow:otherDetails>Coursework 1 Handed out</sow:otherDetails>
            <sow:lab>XML</sow:lab>
        </sow:week>
        <sow:week id="4" test="midterm">
            <sow:topics>XPath, XSLT, XML to HTML using XSLT</sow:topics>
            <sow:lab>XSLT</sow:lab>
        </sow:week>
        <sow:week id="5" test="midterm">
            <sow:topics>Java XML Programming, SAX, DOM and StaX Parsers</sow:topics>
            <sow:otherDetails>Coursework 1 Due</sow:otherDetails>
            <sow:lab>Java XML Parsers</sow:lab>
        </sow:week>
        <sow:week id="6" test="endterm" coursework="2">
            <sow:topics>Java XML Programming (Only 1 lecture)</sow:topics>
            <sow:otherDetails>Mid Term Test for CSF205</sow:otherDetails>
            <sow:lab>Java XML Parsers</sow:lab>
        </sow:week>
        <sow:week id="7" test="endterm" coursework="2">
            <sow:topics>Introduction to HTTP and
                Servlets (only 1 lecture)</sow:topics>
            <sow:lab>Simple Servlets</sow:lab>
        </sow:week>
        <sow:week id="8" test="endterm" coursework="2">
            <sow:topics>Java Servlet Programming and
                Web Application development cycle</sow:topics>
            <sow:lab>Servlets</sow:lab>
        </sow:week>
        <sow:week id="9" test="endterm" coursework="2">
            <sow:topics>Web Application Security and
                Web Services (SOAP, UDDI, WSDL)</sow:topics>
            <sow:otherDetails>Coursework 2 Handed out</sow:otherDetails>
            <sow:lab>Web Services (SOAP, UDDI, WSDL)</sow:lab>
        </sow:week>
        <sow:week id="10" test="endterm">
            <sow:topics>RESTful API Architecture and JSON Data Representation</sow:topics>
            <sow:lab>JSON</sow:lab>
        </sow:week>
        <sow:week id="11" test="endterm">
            <sow:topics>More Frontend (JavaScript, JQuery, AJAX etc.)
                and Backend Web Development (Java, Python, PHP etc.), and Other
                forms of Data Representation (RDF, *SON)</sow:topics>
            <sow:otherDetails>Coursework 2 Due</sow:otherDetails>
            <sow:lab>Catch up Lab Sessions</sow:lab>
        </sow:week>
        <sow:week id="12">
            <sow:topics>EndTerm Test for CSF205</sow:topics>
        </sow:week>
    </sow:lectureSyllabus>
</sow:schemeOfWork>

=== rama-swuni/csf205-2021/week3/CSF205SoWWithXSDNoNS.xml
<?xml version="1.0" encoding="UTF-8"?>
<schemeOfWork courseID="CSF205"
              xmlns="http://www.example.org/sow"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.example.org/sow sow.xsd ">
    <courseDetails>
        <courseTitle>Data Representation, Markup Languages and Web Services</courseTitle>
        <courseDuration length="months">3</courseDuration>
        <courseInstructor>
            <instructor emailID="r.vaidhiyanathan@swansea.ac.uk">Ramalakshmi Vaidhiyanathan</instructor>
        </courseInstructor>
        <courseDates>
            <startDate>23-Sept-2020</startDate>
            <endDate>16-Dec-2020</endDate>
        </courseDates>
    </courseDetails>
    <booksRecommended>
        <book isbn10="0321269667">
            <title>An Introduction to XML and Web Technologies</title>
            <authors>
                <author>Anders MÃ¸ller</author>
                <author>Michael I. Schwartzbach</author>
            </authors>
        </book>
        <book isbn10="0470114878">
            <title>Beginning XML</title>
            <authors>
                <author>David Hunter</author>
            </authors>
        </book>
    </booksRecommended>
    <lectureSyllabus>
        <week id="1" test="midterm" coursework="1">
            <topics>Introduction to Data Representation,
                Data Presentation, Markup Languages, HTML</topics>
            <lab>HTML</lab>
        </week>
        <week id="2" test="midterm" coursework="1">
            <topics>Presentation and Styling of Data using CSS,
                and Web Accessibility</topics>
            <lab>HTML + CSS</lab>
        </week>
        <week id="3" test="midterm" coursework="1">
            <topics>Introduction to Data Representation using XML,
                XML validation using DTD and Schema</topics>
            <otherDetails>Coursework 1 Handed out</otherDetails>
            <lab>XML</lab>
        </week>
        <week id="4" test="midterm">
            <topics>XPath, XSLT, XML to HTML using XSLT</topics>
            <lab>XSLT</lab>
        </week>
        <week id="5" test="midterm">
            <topics>Java XML Programming, SAX, DOM and StaX Parsers</topics>
            <otherDetails>Coursework 1 Due</otherDetails>
            <lab>Java XML Parsers</lab>
        </week>
        <week id="6" test="endterm" coursework="2">
            <topics>Java XML Programming (Only 1 lecture)</topics>
            <otherDetails>Mid Term Test for CSF205</otherDetails>
            <lab>Java XML Parsers</lab>
        </week>
        <week id="7" test="endterm" coursework="2">
            <topics>Introduction to HTTP and
                Servlets (only 1 lecture)</topics>
            <lab>Simple Servlets</lab>
        </week>
        <week id="8" test="endterm" coursework="2">
            <topics>Java Servlet Programming and
                Web Application development cycle</topics>
            <lab>Servlets</lab>
        </week>
        <week id="9" test="endterm" coursework="2">
            <topics>Web Application Security and
                Web Services (SOAP, UDDI, WSDL)</topics>
            <otherDetails>Coursework 2 Handed out</otherDetails>
            <lab>Web Services (SOAP, UDDI, WSDL)</lab>
        </week>
        <week id="10" test="endterm">
            <topics>RESTful API Architecture and JSON Data Representation</topics>
            <lab>JSON</lab>
        </week>
        <week id="11" test="endterm">
            <topics>More Frontend (JavaScript, JQuery, AJAX etc.)
                and Backend Web Development (Java, Python, PHP etc.), and Other
                forms of Data Representation (RDF, *SON)</topics>
            <otherDetails>Coursework 2 Due</otherDetails>
            <lab>Catch up Lab Sessions</lab>
        </week>
        <week id="12">
            <topics>EndTerm Test for CSF205</topics>
        </week>
    </lectureSyllabus>
</schemeOfWork>
